name: Playwright Tests
on:
  workflow_dispatch:

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.42.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest-playwright
          pip install faster-whisper streamlit pytube openai pysubs2 streamlit_ext streamlit_extras
      - name: Download Whisper models and Run Streamlit
        run: |
          mkdir models/ && mkdir models/faster-whisper/
          python3 deploy/download_faster_whisper_models.py
          cd src/
          streamlit run run_app.py &
      - name: Run your tests
        run: pytest browser_test.py
        env:
          HOME: /root
